package com.cmcc.know.entity;

import java.util.Date;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * 
 * ClassName: Knowledge 
 * @Description: TODO 资料库实体
 * @author zengzhibin
 * @date 2019年2月27日
 */

@ApiModel(value="资料库实体",description="资料库实体")
public class Knowledge {
	
	@ApiModelProperty(hidden=true)
    private String hnowId;
	/**
	 * 类型，专业，标题查询 
	 */
	@ApiModelProperty(value="类型，专业，标题模糊查询",required=false)
	private String selectField;
	
	@ApiModelProperty(value="类型ID",required=false)
    private String typeId;
	@ApiModelProperty(value="类型名称",required=false)
    private String typeName;
	@ApiModelProperty(value="专业ID",required=false)
    private String dictionaryId;
	@ApiModelProperty(value="专业名称",required=false)
    private String dictionaryValue;

    @ApiModelProperty(hidden=true)
    private Date createTime;
    @ApiModelProperty(hidden=true)
    private Date sendTime;

    @ApiModelProperty(value="标题",required=false)
    private String title;
    @ApiModelProperty(value="简介",required=false)
    private String brief;
    @ApiModelProperty(value="内容",required=false)
    private String content;
    @ApiModelProperty(value="附件地址",required=false)
    private String attachment;
    @ApiModelProperty(value="状态，0已发布，1未发布",required=false)
    private String status;
    @ApiModelProperty(hidden=true)
    private String delFlag;

    
    public String getSelectField() {
		return selectField;
	}

	public void setSelectField(String selectField) {
		this.selectField = selectField;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_knowledge.hnow_id
     *
     * @return the value of da_knowledge.hnow_id
     *
     * @mbg.generated
     */
    public String getHnowId() {
        return hnowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_knowledge.hnow_id
     *
     * @param hnowId the value for da_knowledge.hnow_id
     *
     * @mbg.generated
     */
    public void setHnowId(String hnowId) {
        this.hnowId = hnowId == null ? null : hnowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_knowledge.type_id
     *
     * @return the value of da_knowledge.type_id
     *
     * @mbg.generated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_knowledge.type_id
     *
     * @param typeId the value for da_knowledge.type_id
     *
     * @mbg.generated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_knowledge.type_name
     *
     * @return the value of da_knowledge.type_name
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_knowledge.type_name
     *
     * @param typeName the value for da_knowledge.type_name
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_knowledge.dictionary_id
     *
     * @return the value of da_knowledge.dictionary_id
     *
     * @mbg.generated
     */
    public String getDictionaryId() {
        return dictionaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_knowledge.dictionary_id
     *
     * @param dictionaryId the value for da_knowledge.dictionary_id
     *
     * @mbg.generated
     */
    public void setDictionaryId(String dictionaryId) {
        this.dictionaryId = dictionaryId == null ? null : dictionaryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_knowledge.dictionary_value
     *
     * @return the value of da_knowledge.dictionary_value
     *
     * @mbg.generated
     */
    public String getDictionaryValue() {
        return dictionaryValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_knowledge.dictionary_value
     *
     * @param dictionaryValue the value for da_knowledge.dictionary_value
     *
     * @mbg.generated
     */
    public void setDictionaryValue(String dictionaryValue) {
        this.dictionaryValue = dictionaryValue == null ? null : dictionaryValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_knowledge.create_time
     *
     * @return the value of da_knowledge.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_knowledge.create_time
     *
     * @param createTime the value for da_knowledge.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_knowledge.send_time
     *
     * @return the value of da_knowledge.send_time
     *
     * @mbg.generated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_knowledge.send_time
     *
     * @param sendTime the value for da_knowledge.send_time
     *
     * @mbg.generated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_knowledge.attachment
     *
     * @return the value of da_knowledge.attachment
     *
     * @mbg.generated
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_knowledge.attachment
     *
     * @param attachment the value for da_knowledge.attachment
     *
     * @mbg.generated
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_knowledge.title
     *
     * @return the value of da_knowledge.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_knowledge.title
     *
     * @param title the value for da_knowledge.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_knowledge.brief
     *
     * @return the value of da_knowledge.brief
     *
     * @mbg.generated
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_knowledge.brief
     *
     * @param brief the value for da_knowledge.brief
     *
     * @mbg.generated
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_knowledge.status
     *
     * @return the value of da_knowledge.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_knowledge.status
     *
     * @param status the value for da_knowledge.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_knowledge.del_flag
     *
     * @return the value of da_knowledge.del_flag
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_knowledge.del_flag
     *
     * @param delFlag the value for da_knowledge.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column da_knowledge.content
     *
     * @return the value of da_knowledge.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column da_knowledge.content
     *
     * @param content the value for da_knowledge.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}